CREATE TABLE IF NOT EXISTS MusicalGenre(
	GenreID SERIAL PRIMARY KEY,
	NameGenre VARCHAR(40) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Musician(
	MusicianID SERIAL PRIMARY KEY,
	NameMusician VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS Album(
	AlbumID SERIAL PRIMARY KEY,
	NameAlbum VARCHAR(60) NOT NULL,
	ReleaseAlbum INTEGER NOT NULL 
);

CREATE TABLE IF NOT EXISTS Track(
	TrackID SERIAL PRIMARY KEY,
	AlbumID INTEGER NOT NULL REFERENCES Album(AlbumID),
	NameTrack VARCHAR(100) NOT NULL,
	LengthTrack INTEGER NOT NULL 
);

CREATE TABLE IF NOT EXISTS Collection(
	CollectionID SERIAL PRIMARY KEY,
	NameCollection VARCHAR(100) NOT NULL,
	ReleaseCollection INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS MusiciansGenres(
	GenreID INTEGER REFERENCES MusicalGenre(GenreID),
	MusicianID INTEGER REFERENCES Musician(MusicianID),
	CONSTRAINT mg PRIMARY KEY (GenreID, MusicianID)
);

CREATE TABLE IF NOT EXISTS MusiciansAlbums(
	AlbumID INTEGER REFERENCES Album(AlbumID),
	MusicianID INTEGER REFERENCES Musician(MusicianID),
	CONSTRAINT ma PRIMARY KEY (AlbumID, MusicianID)
);

CREATE TABLE IF NOT EXISTS TracksCollections(
	TrackID INTEGER REFERENCES Track(TrackID),
	CollectionID INTEGER REFERENCES Collection(CollectionID),
	CONSTRAINT tc PRIMARY KEY (TrackID, CollectionID)
);
